# Makefile for RplotInclude
# ========================
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/base -I$(IPATH)/general -I$(IPATH)/superdarn
IGNVER=1
OBJS = RplotInclude.o
OUTPUT = RplotInclude
LIBS=-lrplot.1
SLIB=-lm
include $(MAKEBIN)