# Makefile for PostScriptSetText
# ========================
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/base -I$(IPATH)/general -I$(IPATH)/superdarn
IGNVER=1
OBJS = PostScriptSetText.o
OUTPUT = PostScriptSetText
LIBS=-lrps.1
SLIB=-lm
include $(MAKEBIN)