# Makefile for ConvertToInt
# ==============================
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/base
IGNVER=1
OBJS = ConvertToInt.o
OUTPUT = ConvertToInt
LIBS= -lrcnv.1
SLIB= -lm
include $(MAKEBIN)
 





