#  Makefile for igrf library
#  ========================

INCLUDE=-I$(IPATH)/base -I$(IPATH)/analysis
SRC=shval3.c shval.h dihf.c interpshc.c interpshc.h extrapshc.c extrapshc.h \
    magcmp.c igrfcall.c getshc.c getshc.h  
OBJS = shval3.o dihf.o interpshc.o extrapshc.o magcmp.o igrfcall.o getshc.o
SRC = shval3.c dihf.c interpshc.c extrapshc.c magcmp.c igrfcall.c getshc.c
DSTPATH=$(LIBPATH)
OUTPUT = igrf
LINK="1"
include $(MAKELIB)


 















