# Makefile for RplotLine
# ========================
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/base -I$(IPATH)/general -I$(IPATH)/superdarn
IGNVER=1
OBJS = RplotLine.o
OUTPUT = RplotLine
LIBS=-lrplot.1
SLIB=-lm
include $(MAKEBIN)