# Makefile for nnet_lib
# =======================
# by R.J.Barnes
#
#
INCLUDE=-I$(IPATH)/base -I$(IPATH)/general
SRC=nnet.c
OBJS = nnet.o
DSTPATH=$(LIBPATH)
OUTPUT = rnnet
LINK="1"
include $(MAKELIB)

















