# Makefile for RadarGetOperator
# ======================
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/base -I$(IPATH)/superdarn 
IGNVER=1
OBJS = RadarGetOperator.o
OUTPUT = RadarGetOperator
LIBS=-lradar.1 -lrtime.1 -lrcnv.1 
SLIB=-lm
include $(MAKEBIN)
 
