# Makefile for SImageIndexFree
# =============================
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/base -I$(IPATH)/general -I$(IPATH)/imagery
IGNVER=1
OBJS = SImageIndexFree.o
OUTPUT = SImageIndexFree
LIBS= -lsimage.1 -lrtime.1 -ldmap.1 -lrcnv.1 
SLIB=-lm
include $(MAKEBIN)
 