# Makefile for RplotEndInfo
# ========================
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/base -I$(IPATH)/general -I$(IPATH)/superdarn
IGNVER=1
OBJS = RplotEndInfo.o
OUTPUT = RplotEndInfo
LIBS=-lrplot.1
SLIB=-lm
include $(MAKEBIN)