# Makefile for OldFitCnxRead
# ==========================
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/base -I$(IPATH)/superdarn 
IGNVER=1
OBJS = OldFitCnxRead.o
OUTPUT = OldFitCnxRead
LIBS=-loldfitcnx.1 -lcnx.1 -lrcnv.1 
SLIB=-lm
include $(MAKEBIN)
 
