# Makefile for RplotEllipse
# ========================
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/base -I$(IPATH)/general -I$(IPATH)/superdarn
IGNVER=1
OBJS = RplotEllipse.o
OUTPUT = RplotEllipse
LIBS=-lrplot.1
SLIB=-lm
include $(MAKEBIN)