# Makefile for SImageFseek
# ========================
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/base -I$(IPATH)/general -I$(IPATH)/imagery
IGNVER=1
OBJS = SImageFseek.o
OUTPUT = SImageFseek
LIBS= -lsimage.1 -lrtime.1 -ldmap.1 -lrcnv.1 
SLIB=-lm
include $(MAKEBIN)
 