# Makefile for FrameBufferFreeDash
# ========================
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/base -I$(IPATH)/general 
IGNVER=1
OBJS = FrameBufferFreeDash.o
OUTPUT = FrameBufferFreeDash
LIBS=-lrfbuf.1
SLIB=-lm
include $(MAKEBIN)