# Makefile for OldFitHeaderWrite
# ===============================
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/base -I$(IPATH)/general -I$(IPATH)/superdarn 
IGNVER=1
OBJS = OldFitHeaderWrite.o
OUTPUT = OldFitHeaderWrite
LIBS=-loldfit.1 -lrtime.1 -lrcnv.1 
SLIB=-lm
include $(MAKEBIN)
 
