# Makefile for scaleppmx
# ======================
# Author: R.J.Barnes

SRC=hlpstr.h scaleppmx.c errstr.h

INCLUDE=-I$(IPATH)/base
OBJS = scaleppmx.o
OUTPUT = $(BINPATH)/scaleppmx
LIBS=-lrfbuf.1 -lrxml.1 -lopt.1 
SLIB= -lm
include $(MAKEBIN)

 

