# Makefile for SmrSeek
# =====================
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/base -I$(IPATH)/general -I$(IPATH)/superdarn 
IGNVER=1
OBJS = SmrSeek.o
OUTPUT = SmrSeek
LIBS=-lsmr.1 -lrtime.1 -lrcnv.1 
SLIB=-lm
include $(MAKEBIN)
 
