# Makefile for TimeJulianToYMDHMS
# ===============================
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/general 
IGNVER=1
OBJS = TimeYrsecToYMDHMS.o
OUTPUT = TimeYrsecToYMDHMS
LIBS=-lrtime.1 
SLIB=-lm
include $(MAKEBIN)
 
