# Makefile for PostScriptNewPage
# ========================
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/base -I$(IPATH)/general -I$(IPATH)/superdarn
IGNVER=1
OBJS = PostScriptNewPage.o
OUTPUT = PostScriptNewPage
LIBS=-lrps.1
SLIB=-lm
include $(MAKEBIN)