# Makefile for OldFitInxClose
# ===========================
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/base -I$(IPATH)/general -I$(IPATH)/superdarn 
IGNVER=1
OBJS = OldFitInxClose.o
OUTPUT = OldFitInxClose
LIBS=-loldfit.1 -lrtime.1 -lrcnv.1 
SLIB=-lm
include $(MAKEBIN)
 
