# Makefile for IGRFMagCmp
# =====================
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/analysis 
IGNVER=1
OBJS = IGRFMagCmp.o
OUTPUT = IGRFMagCmp
LIBS= -ligrf.1  
SLIB= -lm
include $(MAKEBIN)
 





