# Makefile for radar library
# ========================
# by R.J.Barnes
#
#
INCLUDE=-I$(IPATH)/base -I$(IPATH)/general -I$(IPATH)/superdarn
SRC=radar.c
OBJS = radar.o
DSTPATH=$(LIBPATH)
OUTPUT = radar
LINK="1"
include $(MAKELIB)



