# Makefile for radarscan library
# ============================== 
# by R.J.Barnes
#


INCLUDE=-I$(IPATH)/base -I$(IPATH)/general -I$(IPATH)/superdarn
SRC = radarscan.c  
OBJS = radarscan.o
LINK="1"
DSTPATH=$(LIBPATH)
OUTPUT = rscan
include $(MAKELIB)


 

 















