# Makefile for fitacfex library
# ========================
# by R.J.Barnes
#

INCLUDE=-I$(IPATH)/base -I$(IPATH)/superdarn -I$(IPATH)/radarqnx4

SRC = fitacfex.c 
OBJS = fitacfex.o
LINK="1"
DSTPATH=$(LIBPATH)
OUTPUT = fitacfex
include $(MAKELIB)



