# Makefile for ConvertToDouble
# ==============================
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/base
IGNVER=1
OBJS = ConvertToDouble.o
OUTPUT = ConvertToDouble
LIBS= -lrcnv.1
SLIB= -lm
include $(MAKEBIN)
 





