# Makefile for rpos library
# ==========================
# by R.J.Barnes
#


INCLUDE=-I$(IPATH)/base -I$(IPATH)/general -I$(IPATH)/analysis -I$(IPATH)/superdarn 
SRC = cnvtcoord.c calcvector.c invmag.c geodtgc.h
OBJS = cnvtcoord.o calcvector.o invmag.o  
DSTPATH=$(LIBPATH)
OUTPUT = rpos
LINK="1"
include $(MAKELIB)


 

 















