# Makefile for SZAAngle
# =====================
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/imagery -I$(IPATH)/general 
IGNVER=1
OBJS = SZAAngle.o
OUTPUT = SZAAngle
LIBS= -lsza.1 -lrtime.1 
SLIB=-lm
include $(MAKEBIN)
 
