# Makefile for GEOPGsmGse
# =======================
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/analysis
IGNVER=1
OBJS = GEOPGsmGse.o
OUTPUT = GEOPGsmGse
LIBS= -lgeop.1
SLIB= -lm
include $(MAKEBIN)
 





