# Makefile for script library
# ===========================
# by R.J.Barnes
#
#
INCLUDE=-I$(IPATH)/base
SRC=rscript.c rscriptHTML.c
OBJS = rscript.o rscriptHTML.o
DSTPATH=$(LIBPATH)
OUTPUT = rscript
LINK="1"
include $(MAKELIB)

















