# Makefile for scaleppm
# =====================
# Author: R.J.Barnes

SRC=hlpstr.h errstr.h scaleppm.c

INCLUDE=-I$(IPATH)/base
OBJS = scaleppm.o
OUTPUT = $(BINPATH)/scaleppm
LIBS=-lrfbuf.1 -lrxml.1 -lopt.1 
SLIB= -lm
include $(MAKEBIN)

 

