# Makefile for poly
# =================
# by R.J.Barnes
#
#
INCLUDE=-I$(IPATH)/general
SRC=poly.c isect.c transform.c
OBJS =  poly.o isect.o transform.o
LINK="1"
DSTPATH=$(LIBPATH)
OUTPUT = poly
include $(MAKELIB)


 

 





