# Makefile for RadarYMDHMSGetSite
# ======================
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/base -I$(IPATH)/superdarn 
IGNVER=1
OBJS = RadarYMDHMSGetSite.o
OUTPUT = RadarYMDHMSGetSite
LIBS=-lradar.1 -lrtime.1 -lrcnv.1 
SLIB=-lm
include $(MAKEBIN)
 
