# Makefile for FrameBufferEllipse
# ========================
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/base -I$(IPATH)/general 
IGNVER=1
OBJS = FrameBufferEllipse.o
OUTPUT = FrameBufferEllipse
LIBS=-lrfbuf.1
SLIB=-lm
include $(MAKEBIN)