# Makefile for RplotInfo
# ========================
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/base -I$(IPATH)/general -I$(IPATH)/superdarn
IGNVER=1
OBJS = RplotInfo.o
OUTPUT = RplotInfo
LIBS=-lrplot.1
SLIB=-lm
include $(MAKEBIN)