# Makefile for RplotBezier
# ========================
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/base -I$(IPATH)/general -I$(IPATH)/superdarn
IGNVER=1
OBJS = RplotBezier.o
OUTPUT = RplotBezier
LIBS=-lrplot.1
SLIB=-lm
include $(MAKEBIN)