# Makefile for map library
# ========================
# by R.J.Barnes
#
#
INCLUDE=-I$(IPATH)/base -I$(IPATH)/general
SRC=plot.c transform.c clip.c wrap.c load.c
OBJS = plot.o transform.o clip.o wrap.o load.o
DSTPATH=$(LIBPATH)
OUTPUT = rmap
LINK="1"
include $(MAKELIB)

















