# Makefile for RplotColorStringRGB
# ========================
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/base -I$(IPATH)/general -I$(IPATH)/superdarn
IGNVER=1
OBJS = RplotColorStringRGB.o
OUTPUT = RplotColorStringRGB
LIBS=-lrplot.1
SLIB=-lm
include $(MAKEBIN)