# Makefile for gtablewrite library
# ================================ 
# by R.J.Barnes
#
#
INCLUDE=-I$(IPATH)/base -I$(IPATH)/general -I$(IPATH)/superdarn 
SRC = gtablewrite.c 
OBJS = gtablewrite.o 
LINK="1"
DSTPATH=$(LIBPATH)
OUTPUT = gtabw
include $(MAKELIB)
 