# Makefile for OptionFreeFile
# ===========================
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/base
IGNVER=1
OBJS = OptionFreeFile.o
OUTPUT = OptionFreeFile
LIBS= -lopt.1
SLIB= -lm
include $(MAKEBIN)
 





