# Makefile for XwinOpenDisplay
# =============================
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/base 
IGNVER=1
OBJS = XwinOpenDisplay.o
OUTPUT = XwinOpenDisplay
LIBS=-lrfbuf.1 -lxwin.1 
SLIB=-lm
include $(MAKEBIN)
 
