# Makefile for ConvertFromFloat
# =============================
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/base
IGNVER=1
OBJS = ConvertFromFloat.o
OUTPUT = ConvertFromFloat
LIBS= -lrcnv.1
SLIB= -lm
include $(MAKEBIN)
 





