# Makefile for fit_cp
# ===================
# Author: R.J.Barnes
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/base -I$(IPATH)/general -I$(IPATH)/superdarn
OBJS = fit_cp.o
SRC=hlpstr.h errstr.h fit_cp.c
OUTPUT = $(BINPATH)/fit_cp
LIBS=-loldfit.1 -lfit.1 -lrscan.1 -ldmap.1 -lopt.1 -lrtime.1 -lrcnv.1
SLIB=-lm
include $(MAKEBIN)
 

