# Makefile for make_time
# ======================
# Author: R.J.Barnes
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/base -I$(IPATH)/general -I$(IPATH)/superdarn
OBJS = make_time.o
SRC=hlpstr.h errstr.h make_time.c
OUTPUT = $(BINPATH)/make_time
LIBS=-lopt.1 -lrtime.1 
SLIB=-lm
include $(MAKEBIN)
 

