# Makefile for RplotClip
# ========================
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/base -I$(IPATH)/general -I$(IPATH)/superdarn
IGNVER=1
OBJS = RplotClip.o
OUTPUT = RplotClip
LIBS=-lrplot.1
SLIB=-lm
include $(MAKEBIN)