# Makefile for cat_raw
# ====================
# Author: R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/base -I$(IPATH)/general -I$(IPATH)/superdarn
OBJS = cat_raw.o
SRC=hlpstr.h errstr.h cat_raw.c
OUTPUT = $(BINPATH)/cat_raw
LIBS=-loldraw.1 -lopt.1 -lrtime.1 -lrcnv.1  
SLIB=-lm
include $(MAKEBIN)
 

