# Makefile for ConvertFwriteFloat
# ==============================
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/base
IGNVER=1
OBJS = ConvertFwriteFloat.o
OUTPUT = ConvertFwriteFloat
LIBS= -lrcnv.1
SLIB= -lm
include $(MAKEBIN)
 





