# Makefile for RplotMake
# ========================
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/base -I$(IPATH)/general -I$(IPATH)/superdarn
IGNVER=1
OBJS = RplotMake.o
OUTPUT = RplotMake
LIBS=-lrplot.1
SLIB=-lm
include $(MAKEBIN)