# Makefile for Frame Buffer Library
# =================================
# by R.J.Barnes
#
#
INCLUDE=-I$(IPATH)/base
SRC=imagedb.c
OBJS=imagedb.o
DSTPATH=$(LIBPATH)
OUTPUT = imagedb
LINK="1"
include $(MAKELIB)

















