# Makefile for AACGMLoadCoef
# ==========================
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/analysis 
IGNVER=1
OBJS = AACGMLoadCoef.o
OUTPUT = AACGMLoadCoef
LIBS= -laacgm.1  
SLIB=-lm
include $(MAKEBIN)
 





