# Makefile for XwinFreeWidnow
# ===========================
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/base 
IGNVER=1
OBJS = XwinFreeWindow.o
OUTPUT = XwinFreeWindow
LIBS=-lrfbuf.1 -lxwin.1 
SLIB=-lm
include $(MAKEBIN)
 
