# Makefile for PostScriptLine
# ========================
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/base -I$(IPATH)/general -I$(IPATH)/superdarn
IGNVER=1
OBJS = PostScriptLine.o
OUTPUT = PostScriptLine
LIBS=-lrps.1
SLIB=-lm
include $(MAKEBIN)