# Makefile for fitacftofit
# ========================
# Author: R.J.Barnes
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/base -I$(IPATH)/general -I$(IPATH)/superdarn
OBJS =  fitacftofit.o
SRC=hlpstr.h errstr.h fitacftofit.c
OUTPUT = $(BINPATH)/fitacftofit
LIBS= -loldfit.1 -lfit.1 -lrscan.1 -lradar.1 -ldmap.1 -lopt.1 -lrtime.1 -lrcnv.1 
SLIB=-lm
include $(MAKEBIN)
 

