# Makefile for padppm
# ===================
# Author: R.J.Barnes

SRC=hlpstr.h errstr.h padppm.c

INCLUDE=-I$(IPATH)/base
OBJS = padppm.o
OUTPUT = $(BINPATH)/padppm
LIBS=-lrfbuf.1 -lrxml.1 -lopt.1 
SLIB= -lm
include $(MAKEBIN)
