# Makefile for DataMapEncodeBuffer
# ================================
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/base -I$(IPATH)/general 
IGNVER=1
OBJS = DataMapEncodeBuffer.o
OUTPUT = DataMapEncodeBuffer
LIBS=-ldmap.1 -lrcnv.1 
SLIB=-lm
include $(MAKEBIN)
 
