# Makefile for ConvertReadFloat
# =============================
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/base
IGNVER=1
OBJS = ConvertReadFloat.o
OUTPUT = ConvertReadFloat
LIBS= -lrcnv.1
SLIB= -lm
include $(MAKEBIN)
 





