# Makefile for ppmxd
# ==================
# Author: R.J.Barnes

INCLUDE=-I$(IPATH)/base
SRC=ppmxd.c
OBJS = ppmxd.o
SRC=hlpstr.h errstr.h ppmxd.c
OBJS = ppmxd.o
OUTPUT = $(BINPATH)/ppmxd
LIBS=-lrfbuf.1 -lrxml.1 -lopt.1
XLIB=-lxwin.1
SLIB= -lm 
include $(MAKEBIN)

 

