# Makefile for FrameBufferImage
# ========================
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/base -I$(IPATH)/general 
IGNVER=1
OBJS = FrameBufferImage.o
OUTPUT = FrameBufferImage
LIBS=-lrfbuf.1
SLIB=-lm
include $(MAKEBIN)