# Makefile for ConvertToFloat
# ==============================
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/base
IGNVER=1
OBJS = ConvertToFloat.o
OUTPUT = ConvertToFloat
LIBS= -lrcnv.1
SLIB= -lm
include $(MAKEBIN)
 





