# Makefile for RplotMatrixTransform
# ========================
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/base -I$(IPATH)/general -I$(IPATH)/superdarn
IGNVER=1
OBJS = RplotMatrixTransform.o
OUTPUT = RplotMatrixTransform
LIBS=-lrplot.1
SLIB=-lm
include $(MAKEBIN)