# Makefile for ConvertReadDouble
# =====================--=======
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/base
IGNVER=1
OBJS = ConvertReadDouble.o
OUTPUT = ConvertReadDouble
LIBS= -lrcnv.1
SLIB= -lm
include $(MAKEBIN)
 





