# Makefile for SGP4Setup
# ==========================
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/general -I$(IPATH)/analysis 
IGNVER=1
OBJS = SGP4Setup.o
OUTPUT = SGP4Setup
LIBS= -lrtime.1 -lsgp4.1  
SLIB=-lm
include $(MAKEBIN)
 
