# Makefile for RplotMakeDashString
# ========================
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/base -I$(IPATH)/general -I$(IPATH)/superdarn
IGNVER=1
OBJS = RplotMakeDashString.o
OUTPUT = RplotMakeDashString
LIBS=-lrplot.1
SLIB=-lm
include $(MAKEBIN)