# Makefile for XwinCloseDisplay
# =============================
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/base 
IGNVER=1
OBJS = XwinCloseDisplay.o
OUTPUT = XwinCloseDisplay
LIBS=-lrfbuf.1 -lxwin.1 
SLIB=-lm
include $(MAKEBIN)
 
