# Makefile for cat_fit
# ====================
# Author: R.J.Barnes
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/base -I$(IPATH)/general -I$(IPATH)/superdarn
OBJS = cat_fit.o
SRC=hlpstr.h errstr.h cat_fit.c
OUTPUT = $(BINPATH)/cat_fit
LIBS=-loldfit.1 -lrscan.1 -lopt.1 -lrtime.1 -lrcnv.1 
SLIB=-lm
include $(MAKEBIN)
 

