# Makefile for OldFitInxFclose
# ============================
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/base -I$(IPATH)/general -I$(IPATH)/superdarn 
IGNVER=1
OBJS = OldFitInxFclose.o
OUTPUT = OldFitInxFclose
LIBS=-loldfit.1 -lrtime.1 -lrcnv.1 
SLIB=-lm
include $(MAKEBIN)
 
