# Makefile for trim_raw
# =====================
# Author: R.J.Barnes#
#

INCLUDE=-I$(IPATH)/base -I$(IPATH)/general -I$(IPATH)/superdarn
OBJS = trim_raw.o
SRC=hlpstr.h errstr.h trim_raw.c
OUTPUT = $(BINPATH)/trim_raw
LIBS=-loldraw.1 -lraw.1 -lopt.1 -ldmap.1 -lrtime.1 -lrcnv.1 
SLIB=-lm
include $(MAKEBIN)
 

