# Makefile for ppmtoxml
# =====================
# Author: R.J.Barnes

INCLUDE=-I$(IPATH)/base
SRC=ppmtoxml.c
OBJS = ppmtoxml.o
SRC=hlpstr.h errstr.h ppmtoxml.c
OBJS = ppmtoxml.o
OUTPUT = $(BINPATH)/ppmtoxml
LIBS=-lrfbuf.1 -lrxml.1 -lopt.1 
SLIB= -lm
include $(MAKEBIN)


 















