#  Makefile for grplot
#  ===================

INCLUDE=-I$(IPATH)/base -I$(IPATH)/general
SRC = ignore.c include.c block.c attrib.c string.c int.c float.c value.c tick.c limit.c index.c extent.c dimension.c point.c symbolstore.c make.c axis.c axisvalue.c title.c label.c labelvalue.c zero.c box.c bezier.c line.c shape.c polygon.c text.c image.c imagename.c fitimage.c fitimagename.c fill.c bar.c panel.c body.c symboldraw.c symbol.c grplot.c lineplot.c fillplot.c barplot.c symbolplot.c

OBJS = ignore.o include.o block.o attrib.o string.o int.o float.o value.o tick.o limit.o index.o extent.o dimension.o point.o symbolstore.o make.o axis.o axisvalue.o title.o label.o labelvalue.o zero.o box.o bezier.o line.o shape.o polygon.o text.o image.o imagename.o fitimage.o fitimagename.o fill.o bar.o panel.o body.o symboldraw.o symbol.o grplot.o lineplot.o fillplot.o barplot.o symbolplot.o

DSTPATH=$(LIBPATH)
OUTPUT = grplot
LINK="1"
include $(MAKELIB)




 















