# Makefile for OldFitHeaderFwrite
# ===============================
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/base -I$(IPATH)/general -I$(IPATH)/superdarn 
IGNVER=1
OBJS = OldFitHeaderFwrite.o
OUTPUT = OldFitHeaderFwrite
LIBS=-loldfit.1 -lrtime.1 -lrcnv.1 
SLIB=-lm
include $(MAKEBIN)
 
