# Makefile for ConvertFromDouble
# ==============================
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/base
IGNVER=1
OBJS = ConvertFromDouble.o
OUTPUT = ConvertFromDouble
LIBS= -lrcnv.1
SLIB= -lm
include $(MAKEBIN)
 





