#  Makefile for dmapblkinx
#  =======================

INCLUDE=-I$(IPATH)/base -I$(IPATH)/general 
SRC=dmapblkinx.c hlpstr.h
OBJS =dmapblkinx.o
OUTPUT = $(BINPATH)/dmapblkinx
LIBS= -lopt.1 -ldmap.1 -lrcnv.1
SLIB= -lm
include $(MAKEBIN)

