# Makefile for FrameBufferMakeDash
# ========================
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/base -I$(IPATH)/general 
IGNVER=1
OBJS = FrameBufferMakeDash.o
OUTPUT = FrameBufferMakeDash
LIBS=-lrfbuf.1
SLIB=-lm
include $(MAKEBIN)