# Makefile for RplotEndPlot
# ========================
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/base -I$(IPATH)/general -I$(IPATH)/superdarn
IGNVER=1
OBJS = RplotEndPlot.o
OUTPUT = RplotEndPlot
LIBS=-lrplot.1
SLIB=-lm
include $(MAKEBIN)