# Makefile for FrameBufferFontDBLoad
# ==================================
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/base
IGNVER=1
OBJS = FrameBufferFontDBLoad.o
OUTPUT = FrameBufferFontDBLoad
LIBS=-lfontdb.1 -lrfbuf.1 -lrxml.1
SLIB=-lm
include $(MAKEBIN)