# Makefile for GEOPGsmGSE
# =======================
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/analysis
IGNVER=1
OBJS = GEOPGsmGeo.o
OUTPUT = GEOPGsmGeo
LIBS= -lgeop.1
SLIB= -lm
include $(MAKEBIN)
 





