# Makefile for gtable library
# =========================== 
# by R.J.Barnes
#
#
INCLUDE=-I$(IPATH)/base -I$(IPATH)/general -I$(IPATH)/superdarn 
SRC = gtable.c 
OBJS = gtable.o 

LINK="1"
DSTPATH=$(LIBPATH)
OUTPUT = gtable
include $(MAKELIB)
 

 





