# Makefile for TimeJulianToYMDHMS
# ==============================
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/general 
IGNVER=1
OBJS = TimeJulianToYMDHMS.o
OUTPUT = TimeJulianToYMDHMS
LIBS=-lrtime.1 
SLIB=-lm
include $(MAKEBIN)
 
