# Makefile for oldgrid library
# =========================== 
# by R.J.Barnes
#
#
INCLUDE=-I$(IPATH)/base -I$(IPATH)/general -I$(IPATH)/superdarn
SRC = oldreadgrid.c oldwritegrid.c 
OBJS = oldreadgrid.o oldwritegrid.o

LINK="1"
DSTPATH=$(LIBPATH)
OUTPUT = oldgrd
include $(MAKELIB)
 

 





