#  Makefile showcode.cgi
#  =====================

INCLUDE=-I$(IPATH)/base -I$(IPATH)/general
SRC= loadconfig.c loadconfig.h query.c query.h convert.c convert.h ssi.c \
 ssi.h show.c show.h post.c post.h
OBJS = loadconfig.o query.o convert.o ssi.o show.o post.o
OUTPUT = $(BINPATH)/show.cgi 
SLIB= -lm
LIBS=-lrscript.1 -lreval.1 -lrcgi.1 -lrxmldoc.1 -lrxmldb.1 -ltagdb.1 -lrxml.1
include $(MAKEBIN)


 















