# Makefile for XMLMake
# ========================
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/base -I$(IPATH)/general -I$(IPATH)/superdarn
IGNVER=1
OBJS = XMLMake.o
OUTPUT = XMLMake
LIBS=-lrxml.1
SLIB=-lm
include $(MAKEBIN)