#  Makefile showcode.cgi
#  =====================

INCLUDE=-I$(IPATH)/base
SRC= loadconfig.c loadconfig.h convert.c convert.h ssi.c ssi.h showcode.c showcode.h post.c post.h
OBJS = loadconfig.o convert.o ssi.o showcode.o post.o
OUTPUT = $(BINPATH)/showcode.cgi 
SLIB= -lm
LIBS=-lrscript.1 -lrcgi.1 -lrxmldoc.1 -lrxmldb.1 -ltagdb.1 -lrxml.1
include $(MAKEBIN)


 















