# Makefile for RplotEndEmbed
# ========================
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/base -I$(IPATH)/general -I$(IPATH)/superdarn
IGNVER=1
OBJS = RplotEndEmbed.o
OUTPUT = RplotEndEmbed
LIBS=-lrplot.1
SLIB=-lm
include $(MAKEBIN)