# Makefile for CSDReadRadarScan
# =============================
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/base -I$(IPATH)/general -I$(IPATH)/superdarn 
IGNVER=1
OBJS = CSDReadRadarScan.o
OUTPUT = CSDReadRadarScan
LIBS=-lcsd.1 -lrscan.1 -lrtime.1 -lrcnv.1 
SLIB=-lm
include $(MAKEBIN)
 
