# Makefile for GEOPGeoGsm
# =======================
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/analysis 
IGNVER=1
OBJS = GEOPGeoGsm.o
OUTPUT = GEOPGeoGsm
LIBS= -lgeop.1
SLIB= -lm
include $(MAKEBIN)
 





