# Makefile for ConnexReadMem
# ==========================
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/base
IGNVER=1
OBJS = ConnexReadMem.o
OUTPUT = ConnexReadMem
LIBS= -lcnx.1
SLIB= -lm
include $(MAKEBIN)
 
