# Makefile for geo_map library
# ==========================
# by R.J.Barnes
#
#
INCLUDE=-I$(IPATH)/base -I$(IPATH)/general -I$(IPATH)/analysis \
        -I$(IPATH)/imagery
SRC =  geomap.c 
OBJS = geomap.o
LINK="1"
DSTPATH=$(LIBPATH)
OUTPUT = gmap
include $(MAKELIB)


 

 





