# Makefile for TimeReadClock
# ==========================
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/general 
IGNVER=1
OBJS = TimeReadClock.o
OUTPUT = TimeReadClock
LIBS=-lrtime.1 
SLIB=-lm
include $(MAKEBIN)
 
