# Makefile for ConvertFwriteInt
# =============================
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/base
IGNVER=1
OBJS = ConvertFwriteInt.o
OUTPUT = ConvertFwriteInt
LIBS= -lrcnv.1
SLIB= -lm
include $(MAKEBIN)
 





