# Makefile for RplotImage
# ========================
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/base -I$(IPATH)/general -I$(IPATH)/superdarn
IGNVER=1
OBJS = RplotImage.o
OUTPUT = RplotImage
LIBS=-lrplot.1 -lrfbuf.1 -lrxml.1
SLIB=-lm
include $(MAKEBIN)