# Makefile for xml library
# ========================
# by R.J.Barnes
#
#
INCLUDE=-I$(IPATH)/base
SRC=rxmldb.c table.c element.c entity.c buffer.c tree.c
OBJS = rxmldb.o table.o element.o entity.o buffer.o tree.o 
DSTPATH=$(LIBPATH)
OUTPUT = rxmldb
LINK="1"
include $(MAKELIB)

















