# Makefile for ConvertWriteShort
# =============================
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/base
IGNVER=1
OBJS = ConvertWriteShort.o
OUTPUT = ConvertWriteShort
LIBS= -lrcnv.1
SLIB= -lm
include $(MAKEBIN)
 





