# Makefile for xmltoppm
# =====================
# Author: R.J.Barnes

INCLUDE=-I$(IPATH)/base
SRC=xmltoppm.c
OBJS = xmltoppm.o
SRC=hlpstr.h errstr.h xmltoppm.c
OBJS = xmltoppm.o
OUTPUT = $(BINPATH)/xmltoppm
LIBS=-lrxml.1 -lrfbuf.1 -lopt.1 
SLIB= -lm
include $(MAKEBIN)

 

