# Makefile for XMLCallEnd
# ========================
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/base -I$(IPATH)/general -I$(IPATH)/superdarn
IGNVER=1
OBJS = XMLCallEnd.o
OUTPUT = XMLCallEnd
LIBS=-lrxml.1
SLIB=-lm
include $(MAKEBIN)