# Makefile for FrameBufferLine
# ========================
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/base -I$(IPATH)/general 
IGNVER=1
OBJS = FrameBufferLine.o
OUTPUT = FrameBufferLine
LIBS=-lrfbuf.1
SLIB=-lm
include $(MAKEBIN)