#  Makefile for inxdump
#  ====================

INCLUDE=-I$(IPATH)/base -I$(IPATH)/general 
SRC=inxdump.c hlpstr.h
OBJS =inxdump.o
OUTPUT = $(BINPATH)/inxdump

LIBS= -lopt.1 -lrtime.1 -lrcnv.1
SLIB= -lm
include $(MAKEBIN)

