# Makefile for ConvertToShort
# ===========================
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/base
IGNVER=1
OBJS = ConvertToShort.o
OUTPUT = ConvertToShort
LIBS= -lrcnv.1
SLIB= -lm
include $(MAKEBIN)
 





