# Makefile for RplotFree
# ========================
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/base -I$(IPATH)/general -I$(IPATH)/superdarn
IGNVER=1
OBJS = RplotFree.o
OUTPUT = RplotFree
LIBS=-lrplot.1
SLIB=-lm
include $(MAKEBIN)