# Makefile for time library
# =========================
# by R.J.Barnes
#
#
INCLUDE=-I$(IPATH)/general
SRC=time.c read.c
OBJS = time.o read.o
DSTPATH=$(LIBPATH)
OUTPUT = rtime
LINK="1"
include $(MAKELIB)

















