# Makefile for Geomap
# ===================
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/base -I$(IPATH)/general -I$(IPATH)/imagery
IGNVER=1
OBJS = Geomap.o
OUTPUT = Geomap
LIBS= -lgmap.1 -lraster.1  -lrmap.1 -lpoly.1 -lrplot.1 -lrfbuf.1 -lrxml.1 -lrcnv.1
SLIB=-lm
include $(MAKEBIN)
 


