# Makefile for RCDFVarNumZ
# ========================
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/analysis -I$(CDF_PATH)/include
IGNVER=1
OBJS = RCDFVarNumZ.o
OUTPUT = RCDFVarNumZ
LIBS= -lrcdf.1 -L$(CDF_PATH)/lib -lcdf 
SLIB= -lm
include $(MAKEBIN)
 





