# Makefile for grid library
# =========================== 
# by R.J.Barnes
#
#
INCLUDE=-I$(IPATH)/base -I$(IPATH)/general -I$(IPATH)/superdarn
SRC = addgrid.c avggrid.c copygrid.c integrategrid.c mergegrid.c \
       readgrid.c writegrid.c sortgrid.c gridseek.c gridinx.c
OBJS = addgrid.o avggrid.o copygrid.o integrategrid.o mergegrid.o \
       readgrid.o writegrid.o sortgrid.o gridseek.o gridinx.o

LINK="1"
DSTPATH=$(LIBPATH)
OUTPUT = grd
include $(MAKELIB)
 

 





