# Makefile for TimeEpochToYMDHMS
# ==============================
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/general 
IGNVER=1
OBJS = TimeEpochToYMDHMS.o
OUTPUT = TimeEpochToYMDHMS
LIBS=-lrtime.1 
SLIB=-lm
include $(MAKEBIN)
 
