# Makefile for OptionProcessFile
# ==============================
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/base
IGNVER=1
OBJS = OptionProcessFile.o
OUTPUT = OptionProcessFile
LIBS= -lopt.1
SLIB= -lm
include $(MAKEBIN)
 





