#  Makefile confirm.cgi
#  ====================

INCLUDE=-I$(IPATH)/base
SRC= loadconfig.c loadconfig.h convert.c convert.h ssi.c ssi.h confirm.c \
     confirm.h post.c post.h
OBJS = loadconfig.o convert.o ssi.o confirm.o post.o 
OUTPUT = $(BINPATH)/confirm.cgi 
SLIB= -lm
LIBS=-lrscript.1 -lrcgi.1 -lrxmldoc.1 -lrxmldb.1 -ltagdb.1 -lrxml.1
include $(MAKEBIN)


 















