# Makefile for RawIndexFree
# =========================
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/base -I$(IPATH)/general -I$(IPATH)/superdarn 
IGNVER=1
OBJS = RawIndexFree.o
OUTPUT = RawIndexFree
LIBS=-lraw.1 -lrtime.1 -ldmap.1 -lrcnv.1 
SLIB=-lm
include $(MAKEBIN)
 
