# Makefile for convert library
# ===========================
# by R.J.Barnes
#
#
INCLUDE=-I$(IPATH)/base
SRC=convert.c
OBJS = convert.o
DSTPATH=$(LIBPATH)
OUTPUT = rcnv
LINK="1"
include $(MAKELIB)

















