#  Makefile for dmapdump
#  =====================

INCLUDE=-I$(IPATH)/base -I$(IPATH)/general 
SRC=dmapdump.c hlpstr.h
OBJS =dmapdump.o
OUTPUT = $(BINPATH)/dmapdump
LIBS= -lopt.1 -ldmap.1 -lrcnv.1
SLIB= -lm
include $(MAKEBIN)

