# Makefile for SGP4GeodeticPosition
# =================================
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/general -I$(IPATH)/analysis 
IGNVER=1
OBJS = SGP4GeodeticPosition.o
OUTPUT = SGP4GeodeticPosition
LIBS= -lrtime.1 -lsgp4.1  
SLIB=-lm
include $(MAKEBIN)
 
