# Makefile for ConvertFreadFloat
# ===============================
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/base
IGNVER=1
OBJS = ConvertFreadFloat.o
OUTPUT = ConvertFreadFloat
LIBS= -lrcnv.1
SLIB= -lm
include $(MAKEBIN)
 





