# Makefile for RawIndexLoad
# ==========================
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/base -I$(IPATH)/general -I$(IPATH)/superdarn 
IGNVER=1
OBJS = RawIndexLoad.o
OUTPUT = RawIndexLoad
LIBS=-lraw.1 -lrtime.1 -ldmap.1 -lrcnv.1 
SLIB=-lm
include $(MAKEBIN)
 
