# Makefile for RplotColor
# ========================
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/base -I$(IPATH)/general -I$(IPATH)/superdarn
IGNVER=1
OBJS = RplotColor.o
OUTPUT = RplotColor
LIBS=-lrplot.1
SLIB=-lm
include $(MAKEBIN)