# Makefile for DataMapAddScalar
# ============================
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/base -I$(IPATH)/general 
IGNVER=1
OBJS = DataMapAddScalar.o
OUTPUT = DataMapAddScalar
LIBS=-ldmap.1 -lrcnv.1 
SLIB=-lm
include $(MAKEBIN)
 
