# Makefile for DataMapRead
# =========================
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/base -I$(IPATH)/general 
IGNVER=1
OBJS = DataMapRead.o
OUTPUT = DataMapRead
LIBS=-ldmap.1 -lrcnv.1 
SLIB=-lm
include $(MAKEBIN)
 
