# Makefile for dattorawacf
# ========================
# Author: R.J.Barnes
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/base -I$(IPATH)/general -I$(IPATH)/superdarn
OBJS=dattorawacf.o
SRC=hlpstr.h errstr.h dattorawacf.c
OUTPUT = $(BINPATH)/dattorawacf
LIBS= -loldraw.1 -lraw.1 -lradar.1 -ldmap.1 -lopt.1 -lrtime.1 -lrcnv.1 
SLIB=-lm
include $(MAKEBIN)
 

