# Makefile for sgp4 library
# ==========================
# by R.J.Barnes
#
#
INCLUDE=-I$(IPATH)/base -I$(IPATH)/general -I$(IPATH)/analysis

SRC = sgp4.c
       
OBJS = sgp4.o
DSTPATH=$(LIBPATH)
LINK="1"
OUTPUT = sgp4
include $(MAKELIB)

 

 





