# Makefile for RadarLoadHardware
# ======================
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/base -I$(IPATH)/superdarn 
IGNVER=1
OBJS = RadarLoadHardware.o
OUTPUT = RadarLoadHardware
LIBS=-lradar.1 -lrtime.1 -lrcnv.1 
SLIB=-lm
include $(MAKEBIN)
 
