# Makefile for RCDFMaxRecZ
# ========================
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/analysis -I$(CDF_PATH)/include
IGNVER=1
OBJS = RCDFMaxRecZ.o
OUTPUT = RCDFMaxRecZ
LIBS= -lrcdf.1 -L$(CDF_PATH)/lib -lcdf 
SLIB= -lm
include $(MAKEBIN)
 





