# Makefile for XwinDisplayEvent
# =============================
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/base 
IGNVER=1
OBJS = XwinDisplayEvent.o
OUTPUT = XwinDisplayEvent
LIBS=-lrfbuf.1 -lxwin.1 
SLIB=-lm
include $(MAKEBIN)
 
