# Makefile for ConvertReadInt
# =============================
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/base
IGNVER=1
OBJS = ConvertReadInt.o
OUTPUT = ConvertReadInt
LIBS= -lrcnv.1
SLIB= -lm
include $(MAKEBIN)
 





