# Makefile for RCDFReadR
# ======================
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/analysis -I$(CDF_PATH)/include
IGNVER=1
OBJS = RCDFReadR.o
OUTPUT = RCDFReadR
LIBS= -lrcdf.1 -L$(CDF_PATH)/lib -lcdf 
SLIB= -lm
include $(MAKEBIN)
 





