# Makefile for test_fit
# =====================
# Author: R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/base -I$(IPATH)/general -I$(IPATH)/superdarn
OBJS = test_fit.o
SRC=test_fit.c hlpstr.h errstr.h
OUTPUT = $(BINPATH)/test_fit
LIBS=-loldfit.1 -lfit.1 -lrscan.1 -ldmap.1 -lopt.1 -lrtime.1 -lrcnv.1
SLIB=-lm
include $(MAKEBIN)
 

