# Makefile for ConnexWriteIP
# ==========================
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/base
IGNVER=1
OBJS = ConnexWriteIP.o
OUTPUT = ConnexWriteIP
LIBS= -lcnx.1
SLIB= -lm
include $(MAKEBIN)
 
