# Makefile for szamap
# ===================
# by R.J.Barnes
#
#
INCLUDE=-I$(IPATH)/base -I$(IPATH)/general -I$(IPATH)/analysis \
        -I$(IPATH)/imagery
SRC =  szamap.c   
OBJS = szamap.o
LINK="1"

DSTPATH=$(LIBPATH)
OUTPUT = szamap
include $(MAKELIB)


 

 





