# Makefile for xml library
# ========================
# by R.J.Barnes
#
#
INCLUDE=-I$(IPATH)/base
SRC=tagdb.c
OBJS = tagdb.o
DSTPATH=$(LIBPATH)
OUTPUT = tagdb
LINK="1"
include $(MAKELIB)

















