# Makefile for RPosRngBmAzmElv
# ====================
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/base -I$(IPATH)/superdarn 
IGNVER=1
OBJS = RPosRngBmAzmElv.o
OUTPUT = RPosRngBmAzmElv
LIBS=-lrpos.1 -lradar.1 -lrtime.1 -lrcnv.1 -laacgm.1 -ligrf.1 
SLIB=-lm
include $(MAKEBIN)
 
