# Makefile for Frame Buffer Library
# =================================
# by R.J.Barnes
#
#
INCLUDE=-I$(IPATH)/base
SRC=fontdb.c

OBJS=fontdb.o
DSTPATH=$(LIBPATH)
OUTPUT = fontdb
LINK="1"
include $(MAKELIB)

















