# Makefile for contour
# =====================
# by R.J.Barnes
#
#
INCLUDE=-I$(IPATH)/base -I$(IPATH)/general
SRC=contour.c 
OBJS = contour.o 
DSTPATH=$(LIBPATH)
OUTPUT = contour
LINK="1"
include $(MAKELIB)

 

 















