# Makefile for FrameBufferXMLEnd
# ========================
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/base -I$(IPATH)/general 
IGNVER=1
OBJS = FrameBufferXMLEnd.o
OUTPUT = FrameBufferXMLEnd
LIBS=-lrfbuf.1
SLIB=-lm
include $(MAKEBIN)