# Makefile for FrameBufferFontDBFind
# ==================================
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/base
IGNVER=1
OBJS = FrameBufferFontDBFind.o
OUTPUT = FrameBufferFontDBFind
LIBS=-lfontdb.1 -lrfbuf.1 -lrxml.1
SLIB=-lm
include $(MAKEBIN)