# Makefile for XMLSetStart
# ========================
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/base -I$(IPATH)/general -I$(IPATH)/superdarn
IGNVER=1
OBJS = XMLSetStart.o
OUTPUT = XMLSetStart
LIBS=-lrxml.1
SLIB=-lm
include $(MAKEBIN)