# Makefile for RplotMakeDash
# ========================
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/base -I$(IPATH)/general -I$(IPATH)/superdarn
IGNVER=1
OBJS = RplotMakeDash.o
OUTPUT = RplotMakeDash
LIBS=-lrplot.1
SLIB=-lm
include $(MAKEBIN)