# Makefile for SGP4TLEToJulian
# ==========================
# by R.J.Barnes
#
#

INCLUDE= -I$(IPATH)/analysis 
IGNVER=1
OBJS = SGP4TLEToJulian.o
OUTPUT = SGP4TLEToJulian
LIBS= -lsgp4.1 -lrtime.1
SLIB=-lm
include $(MAKEBIN)
 
