# Makefile for make_fitinx
# ========================
# Author: R.J.Barnes
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/base -I$(IPATH)/general -I$(IPATH)/superdarn
OBJS = make_fitinx.o
SRC=hlpstr.h errstr.h make_fitinx.c
OUTPUT = $(BINPATH)/make_fitinx
LIBS=-loldfit.1 -lfit.1 -lrscan.1 -lopt.1 -lrcnv.1 -ldmap.1 -lrtime.1
SLIB=-lm
include $(MAKEBIN)
 

