# Makefile for RplotColorStringRGBA
# ========================
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/base -I$(IPATH)/general -I$(IPATH)/superdarn
IGNVER=1
OBJS = RplotColorStringRGBA.o
OUTPUT = RplotColorStringRGBA
LIBS=-lrplot.1
SLIB=-lm
include $(MAKEBIN)