# Makefile for etime
# ==================
# Author: R.J.Barnes
# by R.J.Barnes
#
#
INCLUDE=-I$(IPATH)/base -I$(IPATH)/general
OUTPUT = $(BINPATH)/etime
OBJS=etime.o
SRC=hlpstr.h errstr.h etime.c
OUTPUT = $(BINPATH)/etime
LIBS =-lopt.1 -lrtime.1
SLIB =-lm
include $(MAKEBIN)

 

 

