# Makefile for RplotIn Library
# ===============================
# by R.J.Barnes
#
#
INCLUDE=-I$(IPATH)/base


SRC =  ignore.c matrix.c block.c block.h float.c int.c string.c \
       point.c pointstring.c dimension.c line.c bezier.c shape.c polygon.c \
       text.c image.c imagename.c embed.c include.c plot.c info.c \
       clip.c makeplot.c decode.c


OBJS =  ignore.o matrix.o block.o float.o int.o string.o \
        point.o pointstring.o dimension.o line.o bezier.o shape.o polygon.o \
        text.o image.o imagename.o embed.o include.o plot.o info.o \
        clip.o makeplot.o decode.o
DSTPATH=$(LIBPATH)
OUTPUT = rplotin
LINK="1"
include $(MAKELIB)

















