# Makefile for OldRawHeaderFwrite
# ===============================
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/base -I$(IPATH)/general -I$(IPATH)/superdarn 
IGNVER=1
OBJS = OldRawHeaderFwrite.o
OUTPUT = OldRawHeaderFwrite
LIBS=-loldraw.1 -lrtime.1 -ldmap.1 -lrcnv.1 
SLIB=-lm
include $(MAKEBIN)
 
