# Makefile for dmaptoskeleton
# ===========================
# Author: R.J.Barnes
# Author: R.J.Barnes

INCLUDE=-I$(IPATH)/base -I$(IPATH)/general 
SRC=hlpstr.h errstr.h dmaptoskeleton.c
OBJS =dmaptoskeleton.o
OUTPUT = $(BINPATH)/dmaptoskeleton
LIBS= -lopt.1 -ldmap.1 -lrcnv.1
SLIB= -lm
include $(MAKEBIN)

