# Makefile for ConvertWriteInt
# ============================
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/base
IGNVER=1
OBJS = ConvertWriteInt.o
OUTPUT = ConvertWriteInt
LIBS= -lrcnv.1
SLIB= -lm
include $(MAKEBIN)
 





