# Makefile for ConvertFromInt
# ===========================
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/base
IGNVER=1
OBJS = ConvertFromInt.o
OUTPUT = ConvertFromInt
LIBS= -lrcnv.1
SLIB= -lm
include $(MAKEBIN)
 





