# Makefile for ConvertReadShort
# =============================
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/base
IGNVER=1
OBJS = ConvertReadShort.o
OUTPUT = ConvertReadShort
LIBS= -lrcnv.1
SLIB= -lm
include $(MAKEBIN)
 





