#  Makefile confirm.cgi
#  ====================

INCLUDE=-I$(IPATH)/base
SRC= loadconfig.c loadconfig.h ssi.c ssi.h findorder.c findorder.h \
     convert.c convert.h submit.c submit.h post.c post.h
OBJS = loadconfig.o ssi.o findorder.o convert.o submit.o post.o 
OUTPUT = $(BINPATH)/submit.cgi 
SLIB= -lm
LIBS=-lrscript.1 -lrcgi.1 -lrxmldoc.1 -lrxmldb.1 -ltagdb.1 -lrxml.1
include $(MAKEBIN)


 















