# Makefile for sza
# ================
# by R.J.Barnes
#
#
INCLUDE=-I$(IPATH)/base -I$(IPATH)/general -I$(IPATH)/analysis \
        -I$(IPATH)/imagery
SRC =  sza.c   
OBJS = sza.o
LINK="1"

DSTPATH=$(LIBPATH)
OUTPUT = sza
include $(MAKELIB)


 

 





