# Makefile for oldgtablewrite library
# =================================== 
# by R.J.Barnes
#
#
INCLUDE=-I$(IPATH)/base -I$(IPATH)/general -I$(IPATH)/superdarn 
SRC = oldgtablewrite.c 
OBJS = oldgtablewrite.o 
LINK="1"
DSTPATH=$(LIBPATH)
OUTPUT = oldgtabw
include $(MAKELIB)
 

 





