# Makefile for rplot
# ==================
# Author: R.J.Barnes

INCLUDE=-I$(IPATH)/base
SRC=rplot.c
OBJS = rplot.o
SRC=hlpstr.h errstr.h rplot.c
OBJS = rplot.o
OUTPUT = $(BINPATH)/rplot
LIBS=-lfbpsrplot.1 -lrplot.1 -lrplotin.1 -lrxml.1 -limagedb.1 -lfontdb.1 -lrps.1 -lrfbuf.1 -lopt.1 
XLIB=-lxwin.1
SLIB= -lm
include $(MAKEBIN)

 

