# Makefile for FrameBufferMakeDashString
# ========================
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/base -I$(IPATH)/general 
IGNVER=1
OBJS = FrameBufferMakeDashString.o
OUTPUT = FrameBufferMakeDashString
LIBS=-lrfbuf.1
SLIB=-lm
include $(MAKEBIN)