# Makefile for TimeYMDHMSToJulian
# ==============================
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/general 
IGNVER=1
OBJS = TimeYMDHMSToJulian.o
OUTPUT = TimeYMDHMSToJulian
LIBS=-lrtime.1 
SLIB=-lm
include $(MAKEBIN)
 
