# Makefile for FrameBufferSaveFont
# ========================
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/base -I$(IPATH)/general 
IGNVER=1
OBJS = FrameBufferSaveFont.o
OUTPUT = FrameBufferSaveFont
LIBS=-lrfbuf.1
SLIB=-lm
include $(MAKEBIN)