# Makefile for raster_lib
# =====================
# by R.J.Barnes
#
#
INCLUDE=-I$(IPATH)/general
SRC=raster.c 
OBJS = raster.o 
DSTPATH=$(LIBPATH)
OUTPUT = raster
LINK="1"
include $(MAKELIB)

 

 















