# Makefile for PostScriptRotateMatrix
# ========================
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/base -I$(IPATH)/general -I$(IPATH)/superdarn
IGNVER=1
OBJS = PostScriptRotateMatrix.o
OUTPUT = PostScriptRotateMatrix
LIBS=-lrps.1
SLIB=-lm
include $(MAKEBIN)