# Makefile for SZAEqOfTime
# ========================
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/imagery -I$(IPATH)/general 
IGNVER=1
OBJS = SZAEqOfTime.o
OUTPUT = SZAEqOfTime
LIBS= -lsza.1 -lrtime.1 
SLIB=-lm
include $(MAKEBIN)
 
