# Makefile for SGP4EpochToTsince
# ==============================
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/general -I$(IPATH)/analysis 
IGNVER=1
OBJS = SGP4EpochToTsince.o
OUTPUT = SGP4EpochToTsince
LIBS= -lrtime.1 -lsgp4.1  
SLIB=-lm
include $(MAKEBIN)
 
