# Makefile for ConvertWriteFloat
# ==============================
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/base
IGNVER=1
OBJS = ConvertWriteFloat.o
OUTPUT = ConvertWriteFloat
LIBS= -lrcnv.1
SLIB= -lm
include $(MAKEBIN)
 





