# Makefile for xmltoppmx
# ======================
# Author: R.J.Barnes

INCLUDE=-I$(IPATH)/base
SRC=xmltoppmx.c
OBJS = xmltoppmx.o
SRC=hlpstr.h errstr.h xmltoppmx.c
OBJS = xmltoppmx.o
OUTPUT = $(BINPATH)/xmltoppmx
LIBS=-lrxml.1 -lrfbuf.1 -lopt.1 
SLIB= -lm
include $(MAKEBIN)

 

