# Makefile for RplotText
# ========================
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/base -I$(IPATH)/general -I$(IPATH)/superdarn
IGNVER=1
OBJS = RplotText.o
OUTPUT = RplotText
LIBS=-lrplot.1
SLIB=-lm
include $(MAKEBIN)