# Makefile for OldRawSeek
# =====================
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/base -I$(IPATH)/general -I$(IPATH)/superdarn 
IGNVER=1
OBJS = OldRawSeek.o
OUTPUT = OldRawSeek
LIBS=-loldraw.1 -lrtime.1 -ldmap.1 -lrcnv.1 
SLIB=-lm
include $(MAKEBIN)
 
