# Makefile for xmld
# =================
# Author: R.J.Barnes

INCLUDE=-I$(IPATH)/base
SRC=xmld.c
OBJS = xmld.o
SRC=hlpstr.h errstr.h xmld.c
OBJS = xmld.o
OUTPUT = $(BINPATH)/xmld
LIBS=-lrfbuf.1 -lrxml.1 -lopt.1
XLIB=-lxwin.1
SLIB= -lm 
include $(MAKEBIN)

 

