# Makefile for NNetReadNet
# =========================
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/general 
IGNVER=1
OBJS = NNetReadNet.o
OUTPUT = NNetReadNet
LIBS= -lrnnet.1 -lrcnv.1
SLIB= -lm
include $(MAKEBIN)
 
