# Makefile for xml library
# ========================
# by R.J.Barnes
#
#
INCLUDE=-I$(IPATH)/base
SRC=rxml.c call.c
OBJS = rxml.o call.o
DSTPATH=$(LIBPATH)
OUTPUT = rxml
LINK="1"
include $(MAKELIB)

















