# Makefile for FrameBufferColor
# ========================
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/base -I$(IPATH)/general 
IGNVER=1
OBJS = FrameBufferColor.o
OUTPUT = FrameBufferColor
LIBS=-lrfbuf.1
SLIB=-lm
include $(MAKEBIN)