# Makefile for xmltorplot
# =======================
# Author: R.J.Barnes

INCLUDE=-I$(IPATH)/base
SRC=xmltorplot.c 
OBJS = xmltorplot.o
SRC=hlpstr.h errstr.h xmltorplot.c
OBJS = xmltorplot.o
OUTPUT = $(BINPATH)/xmltorplot
LIBS=-lrplot.1 -lrxml.1 -lrfbuf.1 -lopt.1 
SLIB= -lm
include $(MAKEBIN)

 

