# Makefile for ConvertFreadInt
# ============================
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/base
IGNVER=1
OBJS = ConvertFreadInt.o
OUTPUT = ConvertFreadInt
LIBS= -lrcnv.1
SLIB= -lm
include $(MAKEBIN)
 





