# Makefile for phong library
# ==========================
# by R.J.Barnes
#
#
INCLUDE=-I$(IPATH)/base -I$(IPATH)/general -I$(IPATH)/analysis \
        -I$(IPATH)/imagery
SRC =  phong.c 
OBJS = phong.o
LINK="1"

DSTPATH=$(LIBPATH)
OUTPUT = phong
include $(MAKELIB)


 

 





