# Makefile for SGP4EpochToJdoy
# ============================
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/general -I$(IPATH)/analysis 
IGNVER=1
OBJS = SGP4EpochToJdoy.o
OUTPUT = SGP4EpochToJdoy
LIBS= -lrtime.1 -lsgp4.1  
SLIB=-lm
include $(MAKEBIN)
 
