# Makefile for test_raw
# =====================
# Author: R.J.Barnes#
#

INCLUDE=-I$(IPATH)/base -I$(IPATH)/general -I$(IPATH)/superdarn
OBJS = test_raw.o
SRC=test_raw.c errstr.h hlpstr.h
OUTPUT = $(BINPATH)/test_raw
LIBS=-loldraw.1 -lraw.1 -ldmap.1 -lopt.1 -lrtime.1 -lrcnv.1 
SLIB=-lm
include $(MAKEBIN)
 

