# Makefile for PostScriptFree
# ========================
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/base -I$(IPATH)/general -I$(IPATH)/superdarn
IGNVER=1
OBJS = PostScriptFree.o
OUTPUT = PostScriptFree
LIBS=-lrps.1
SLIB=-lm
include $(MAKEBIN)