# Makefile for PostScriptMakePlot
# ========================
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/base -I$(IPATH)/general -I$(IPATH)/superdarn
IGNVER=1
OBJS = PostScriptMakePlot.o
OUTPUT = PostScriptMakePlot
LIBS=-lrps.1
SLIB=-lm
include $(MAKEBIN)