# Makefile for ppmd
# ==================
# Author: R.J.Barnes

INCLUDE=-I$(IPATH)/base
SRC=ppmd.c
OBJS = ppmd.o
SRC=hlpstr.h errstr.h ppmd.c
OBJS = ppmd.o
OUTPUT = $(BINPATH)/ppmd
LIBS=-lrfbuf.1 -lrxml.1 -lopt.1
XLIB=-lxwin.1
SLIB= -lm 
include $(MAKEBIN)

 

