# Makefile for ConvertBlock
# =========================
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/base
IGNVER=1
OBJS = ConvertBlock.o
OUTPUT = ConvertBlock
LIBS= -lrcnv.1
SLIB= -lm
include $(MAKEBIN)
 





