# Makefile for RplotScaleMatrix
# ========================
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/base -I$(IPATH)/general -I$(IPATH)/superdarn
IGNVER=1
OBJS = RplotScaleMatrix.o
OUTPUT = RplotScaleMatrix
LIBS=-lrplot.1
SLIB=-lm
include $(MAKEBIN)