# Makefile for ConvertFreadShort
# =============================
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/base
IGNVER=1
OBJS = ConvertFreadShort.o
OUTPUT = ConvertFreadShort
LIBS= -lrcnv.1
SLIB= -lm
include $(MAKEBIN)
 





