# Makefile for FrameBufferSetUser
# ========================
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/base -I$(IPATH)/general 
IGNVER=1
OBJS = FrameBufferSetUser.o
OUTPUT = FrameBufferSetUser
LIBS=-lrfbuf.1
SLIB=-lm
include $(MAKEBIN)