# Makefile for SGP4YMDHMSToTsince
# ==============================
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/general -I$(IPATH)/analysis 
IGNVER=1
OBJS = SGP4YMDHMSToTsince.o
OUTPUT = SGP4YMDHMSToTsince
LIBS= -lsgp4.1 -lrtime.1  
SLIB=-lm
include $(MAKEBIN)
 
