# Makefile for TimeYMDHMSToYrsec
# ==============================
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/general 
IGNVER=1
OBJS = TimeYMDHMSToYrsec.o
OUTPUT = TimeYMDHMSToYrsec
LIBS=-lrtime.1 
SLIB=-lm
include $(MAKEBIN)
 
