# Makefile for DataMapWrite
# ===========================
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/base -I$(IPATH)/general 
IGNVER=1
OBJS = DataMapWrite.o
OUTPUT = DataMapWrite
LIBS=-ldmap.1 -lrcnv.1 
SLIB=-lm
include $(MAKEBIN)
 
