# Makefile for ConvertFreadDouble
# ============================
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/base
IGNVER=1
OBJS = ConvertFreadDouble.o
OUTPUT = ConvertFreadDouble
LIBS= -lrcnv.1
SLIB= -lm
include $(MAKEBIN)
 





