# Makefile for simage
# ===================
# by R.J.Barnes
#
#
INCLUDE=-I$(IPATH)/base -I$(IPATH)/general -I$(IPATH)/imagery
SRC =  simagewrite.c simageread.c simageseek.c simageinx.c  
OBJS = simagewrite.o simageread.o simageseek.o simageinx.o
LINK="1"

DSTPATH=$(LIBPATH)
OUTPUT = simage
include $(MAKELIB)


 

 





