# Makefile for FrameBufferSavePPMAlpha
# ========================
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/base -I$(IPATH)/general 
IGNVER=1
OBJS = FrameBufferSavePPMAlpha.o
OUTPUT = FrameBufferSavePPMAlpha
LIBS=-lrfbuf.1
SLIB=-lm
include $(MAKEBIN)