# Makefile for OptionScanFileArg
# ==============================
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/base
IGNVER=1
OBJS = OptionScanFileArg.o
OUTPUT = OptionScanFileArg
LIBS= -lopt.1
SLIB= -lm
include $(MAKEBIN)
 





