# Makefile for sza
# ================
# by R.J.Barnes
#
#
INCLUDE=-I$(IPATH)/base -I$(IPATH)/general -I$(IPATH)/analysis \
        -I$(IPATH)/imagery
SRC = load.c   
OBJS = load.o
LINK="1"
DSTPATH=$(LIBPATH)
OUTPUT = elv
include $(MAKELIB)


 

 





