# Makefile for PostScriptRectangle
# ========================
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/base -I$(IPATH)/general -I$(IPATH)/superdarn
IGNVER=1
OBJS = PostScriptRectangle.o
OUTPUT = PostScriptRectangle
LIBS=-lrps.1
SLIB=-lm
include $(MAKEBIN)