# Makefile for RplotRotateMatrix
# ========================
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/base -I$(IPATH)/general -I$(IPATH)/superdarn
IGNVER=1
OBJS = RplotRotateMatrix.o
OUTPUT = RplotRotateMatrix
LIBS=-lrplot.1
SLIB=-lm
include $(MAKEBIN)