# makefile for DataMapSize
# ===========================
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/base -I$(IPATH)/general 
IGNVER=1
OBJS = DataMapSize.o
OUTPUT = DataMapSize
LIBS=-ldmap.1 -lrcnv.1 
SLIB=-lm
include $(MAKEBIN)
 
