# Makefile for SZASolarLoc
# ========================
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/imagery -I$(IPATH)/general 
IGNVER=1
OBJS = SZASolarLoc.o
OUTPUT = SZASolarLoc
LIBS= -lsza.1 -lrtime.1 
SLIB=-lm
include $(MAKEBIN)
 
