# Makefile for RplotSetText
# ========================
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/base -I$(IPATH)/general -I$(IPATH)/superdarn
IGNVER=1
OBJS = RplotSetText.o
OUTPUT = RplotSetText
LIBS=-lrplot.1
SLIB=-lm
include $(MAKEBIN)