# Makefile for FitReadRadarScan
# =============================
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/base -I$(IPATH)/general -I$(IPATH)/superdarn 
IGNVER=1
OBJS = FitReadRadarScan.o
OUTPUT = FitReadRadarScan
LIBS=-lfit.1 -lrscan.1 -lrtime.1 -ldmap.1 -lrcnv.1 
SLIB=-lm
include $(MAKEBIN)
 
