# Makefile for FrameBufferLoadFont
# ========================
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/base -I$(IPATH)/general 
IGNVER=1
OBJS = FrameBufferLoadFont.o
OUTPUT = FrameBufferLoadFont
LIBS=-lrfbuf.1
SLIB=-lm
include $(MAKEBIN)