# Makefile for TimeYMDHMSToEpoch
# ==============================
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/general 
IGNVER=1
OBJS = TimeYMDHMSToEpoch.o
OUTPUT = TimeYMDHMSToEpoch
LIBS=-lrtime.1 
SLIB=-lm
include $(MAKEBIN)
 
