# Makefile for ConnexWriteMem
# ===========================
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/base
IGNVER=1
OBJS = ConnexWriteMem.o
OUTPUT = ConnexWriteMem
LIBS= -lcnx.1
SLIB= -lm
include $(MAKEBIN)
 
