# Makefile for fitcnx library
# ============================
# by R.J.Barnes
#
#
INCLUDE=-I$(IPATH)/base -I$(IPATH)/general -I$(IPATH)/superdarn
SRC=fitcnx.c decodemsg.c cnxstr.h decodemsg.h 
OBJS = fitcnx.o decodemsg.o 
LINK=1
DSTPATH=$(LIBPATH)
OUTPUT = oldfitcnx
include $(MAKELIB)





