# Makefile for ConvertWriteDouble
# ============================
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/base
IGNVER=1
OBJS = ConvertWriteDouble.o
OUTPUT = ConvertWriteDouble
LIBS= -lrcnv.1
SLIB= -lm
include $(MAKEBIN)
 





