# Makefile for RplotMatrixString
# ========================
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/base -I$(IPATH)/general -I$(IPATH)/superdarn
IGNVER=1
OBJS = RplotMatrixString.o
OUTPUT = RplotMatrixString
LIBS=-lrplot.1
SLIB=-lm
include $(MAKEBIN)