# Makefile for filter library
# ============================== 
# by R.J.Barnes
#


INCLUDE=-I$(IPATH)/base -I$(IPATH)/general -I$(IPATH)/superdarn
SRC = filter.c bound.c checkops.c
OBJS = filter.o bound.o checkops.o
LINK="1"
DSTPATH=$(LIBPATH)
OUTPUT = filter
include $(MAKELIB)


 

 















