# Makefile for RplotMakePlot
# ========================
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/base -I$(IPATH)/general -I$(IPATH)/superdarn
IGNVER=1
OBJS = RplotMakePlot.o
OUTPUT = RplotMakePlot
LIBS=-lrplot.1
SLIB=-lm
include $(MAKEBIN)