# Makefile for AACGMInit
# ======================
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/analysis
IGNVER=1 
OBJS = AACGMInit.o
OUTPUT = AACGMInit
LIBS= -laacgm.1  
SLIB=-lm
include $(MAKEBIN)
 





