# Makefile for scalexml
# =====================
# Author: R.J.Barnes

INCLUDE=-I$(IPATH)/base
SRC=scalexml.c
OBJS = scalexml.o
SRC=hlpstr.h errstr.h scalexml.c
OBJS = scalexml.o
OUTPUT = $(BINPATH)/scalexml
LIBS=-lrfbuf.1 -lrxml.1 -lopt.1 
SLIB= -lm
include $(MAKEBIN)

 

