# Makefile for RplotRectangle
# ========================
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/base -I$(IPATH)/general -I$(IPATH)/superdarn
IGNVER=1
OBJS = RplotRectangle.o
OUTPUT = RplotRectangle
LIBS=-lrplot.1
SLIB=-lm
include $(MAKEBIN)