# Makefile for NNetFltRnd
# =========================
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/general 
IGNVER=1
OBJS = NNetFltRnd.o
OUTPUT = NNetFltRnd
LIBS= -lrnnet.1 -lrcnv.1
SLIB= -lm
include $(MAKEBIN)
 
