# Makefile for OptionProcess
# ==========================
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/base
IGNVER=1
OBJS = OptionProcess.o
OUTPUT = OptionProcess
LIBS= -lopt.1
SLIB= -lm
include $(MAKEBIN)
 





