# Makefile for csd library
# ========================== 
# by R.J.Barnes
#


INCLUDE=-I$(IPATH)/base -I$(IPATH)/general -I$(IPATH)/superdarn
SRC = csdopen.c csdclose.c csdwrite.c csdread.c csdseek.c csdscan.c
OBJS = csdopen.o csdclose.o csdwrite.o csdread.o csdseek.o csdscan.o
LINK="1"

DSTPATH=$(LIBPATH)
OUTPUT = csd
include $(MAKELIB)

