# Makefile for ppmxtoppm
# ======================
# Author: R.J.Barnes

SRC=hlpstr.h errstr.h ppmxtoppm.c

INCLUDE=-I$(IPATH)/base
OBJS = ppmxtoppm.o
OUTPUT = $(BINPATH)/ppmxtoppm
LIBS=-lrfbuf.1 -lrxml.1 -lopt.1 
SLIB= -lm
include $(MAKEBIN)

 

