# Makefile for SGP4Calculate
# ==========================
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/general -I$(IPATH)/analysis 
IGNVER=1
OBJS = SGP4Calculate.o
OUTPUT = SGP4Calculate
LIBS= -lrtime.1 -lsgp4.1  
SLIB=-lm
include $(MAKEBIN)
 
