# Makefile for PostScriptMakeDashString
# ========================
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/base -I$(IPATH)/general -I$(IPATH)/superdarn
IGNVER=1
OBJS = PostScriptMakeDashString.o
OUTPUT = PostScriptMakeDashString
LIBS=-lrps.1
SLIB=-lm
include $(MAKEBIN)