#  Makefile for geop library
#  ========================

INCLUDE=-I$(IPATH)/base -I$(IPATH)/general

OBJS = matcald.o crdnt.o geogsm.o gsegsm.o gsmgeo.o \
       gsmgse.o gsmsm.o smgsm.o
SRC=   matcald.c matcald.h crdnt.c crdnt.h geogsm.c gsegsm.c gsmgeo.c \
       gsmgse.c gsmsm.c smgsm.c
DSTPATH=$(LIBPATH)
OUTPUT = geop
LINK="1"
include $(MAKELIB)


 















