# Makefile for PostScriptColor
# ========================
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/base -I$(IPATH)/general -I$(IPATH)/superdarn
IGNVER=1
OBJS = PostScriptColor.o
OUTPUT = PostScriptColor
LIBS=-lrps.1
SLIB=-lm
include $(MAKEBIN)