# Makefile for SGP4YMDHMSToJdoy
# ============================
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/general -I$(IPATH)/analysis 
IGNVER=1
OBJS = SGP4YMDHMSToJdoy.o
OUTPUT = SGP4YMDHMSToJdoy
LIBS= -lsgp4.1 -lrtime.1
SLIB=-lm
include $(MAKEBIN)
 
