# Makefile for XwinMakeWindow
# =============================
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/base 
IGNVER=1
OBJS = XwinMakeWindow.o
OUTPUT = XwinMakeWindow
LIBS=-lrfbuf.1 -lxwin.1 
SLIB=-lm
include $(MAKEBIN)
 
