# Makefile for FrameBufferClear
# ========================
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/base -I$(IPATH)/general 
IGNVER=1
OBJS = FrameBufferClear.o
OUTPUT = FrameBufferClear
LIBS=-lrfbuf.1
SLIB=-lm
include $(MAKEBIN)