# Makefile for XMLSetComment
# ========================
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/base -I$(IPATH)/general -I$(IPATH)/superdarn
IGNVER=1
OBJS = XMLSetComment.o
OUTPUT = XMLSetComment
LIBS=-lrxml.1
SLIB=-lm
include $(MAKEBIN)