# Makefile for GEOPGseGsm
# =======================
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/analysis 
IGNVER=1
OBJS = GEOPGseGsm.o
OUTPUT = GEOPGseGsm
LIBS= -lgeop.1
SLIB= -lm
include $(MAKEBIN)
 





