# Makefile for FrameBufferBezier
# ========================
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/base -I$(IPATH)/general 
IGNVER=1
OBJS = FrameBufferBezier.o
OUTPUT = FrameBufferBezier
LIBS=-lrfbuf.1
SLIB=-lm
include $(MAKEBIN)