# Makefile for XMLSetText
# ========================
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/base -I$(IPATH)/general -I$(IPATH)/superdarn
IGNVER=1
OBJS = XMLSetText.o
OUTPUT = XMLSetText
LIBS=-lrxml.1
SLIB=-lm
include $(MAKEBIN)