# Makefile for time library
# =========================
# by R.J.Barnes
#
#
INCLUDE=-I$(IPATH)/base -I$(IPATH)/general
SRC=rfile.c
OBJS = rfile.o
DSTPATH=$(LIBPATH)
OUTPUT = rfile
LINK="1"
include $(MAKELIB)

















