# Makefile for ConvertFromShort
# =============================
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/base
IGNVER=1
OBJS = ConvertFromShort.o
OUTPUT = ConvertFromShort
LIBS= -lrcnv.1
SLIB= -lm
include $(MAKEBIN)
 





