# Makefile for ppmxtoxml
# ======================
# Author: R.J.Barnes

SRC=hlpstr.h errstr.h ppmxtoxml.c

INCLUDE=-I$(IPATH)/base
OBJS = ppmxtoxml.o
OUTPUT = $(BINPATH)/ppmxtoxml
LIBS=-lrfbuf.1 -lrxml.1 -lopt.1 
SLIB= -lm
include $(MAKEBIN)

 

