# Makefile for CFitRead
# =====================
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/base -I$(IPATH)/general -I$(IPATH)/superdarn 
IGNVER=1
OBJS = CFitRead.o
OUTPUT = CFitRead
LIBS=-lcfit.1 -lrtime.1 -lrcnv.1 
SLIB=-lm
include $(MAKEBIN)
 
