# Makefile for SGP4DecodeTLE
# ==========================
# by R.J.Barnes
#
#

INCLUDE= -I$(IPATH)/analysis 
IGNVER=1
OBJS = SGP4DecodeTLE.o
OUTPUT = SGP4DecodeTLE
LIBS= -lsgp4.1 -lrtime.1
SLIB=-lm
include $(MAKEBIN)
 
