# Makefile for RplotMatrixMultiply
# ========================
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/base -I$(IPATH)/general -I$(IPATH)/superdarn
IGNVER=1
OBJS = RplotMatrixMultiply.o
OUTPUT = RplotMatrixMultiply
LIBS=-lrplot.1
SLIB=-lm
include $(MAKEBIN)