# Makefile for plot library
# =========================
# by R.J.Barnes
#
#
INCLUDE=-I$(IPATH)/base -I$(IPATH)/general
SRC=rplotgraw_contour.c rplotgraw.c rplotgraw_key.c rplotgstd_key.c \
    rplotg.c rplotg_key.c
OBJS = rplotg_key.o rplotg.o rplotgstd_key.o rplotgraw_key.o \
       rplotgraw_contour.o rplotgraw.o 
DSTPATH=$(LIBPATH)
OUTPUT = plot
LINK="1"
include $(MAKELIB)

















