# Makefile for make_vec
# =====================
# Author: R.J.Barnes
# Author: R.J.Barnes
# by R.J.Barnes
#
#
 
INCLUDE=-I$(IPATH)/base -I$(IPATH)/general -I$(IPATH)/superdarn 
OBJS = make_vec.o

SRC=hlpstr.h errstr.h make_vec.c
OUTPUT = $(BINPATH)/make_vec
LIBS=-lgrd.1 -loldgrd.1 -lradar.1 -ldmap.1 -lrfile.1 -lrtime.1 -lopt.1 -lrcnv.1  
SLIB=-lm
include $(MAKEBIN) 

 

