# Makefile for RplotPolygon
# ========================
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/base -I$(IPATH)/general -I$(IPATH)/superdarn
IGNVER=1
OBJS = RplotPolygon.o
OUTPUT = RplotPolygon
LIBS=-lrplot.1
SLIB=-lm
include $(MAKEBIN)