# Makefile for ConvertBitOrder
# ============================
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/base
IGNVER=1
OBJS = ConvertBitOrder.o
OUTPUT = ConvertBitOrder
LIBS= -lrcnv.1
SLIB= -lm
include $(MAKEBIN)
 





