# Makefile for DataMapFwrite
# ===========================
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/base -I$(IPATH)/general 
IGNVER=1
OBJS = DataMapFwrite.o
OUTPUT = DataMapFwrite
LIBS=-ldmap.1 -lrcnv.1 
SLIB=-lm
include $(MAKEBIN)
 
