# Makefile for RplotEmbed
# ========================
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/base -I$(IPATH)/general -I$(IPATH)/superdarn
IGNVER=1
OBJS = RplotEmbed.o
OUTPUT = RplotEmbed
LIBS=-lrplot.1
SLIB=-lm
include $(MAKEBIN)