# Makefile for NNetBackward
# =========================
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/general 
IGNVER=1
OBJS = NNetBackward.o
OUTPUT = NNetBackward
LIBS= -lrnnet.1 -lrcnv.1
SLIB= -lm
include $(MAKEBIN)
 
