# Makefile for OptionPrintInfo
# ============================
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/base
IGNVER=1
OBJS = OptionPrintInfo.o
OUTPUT = OptionPrintInfo
LIBS= -lopt.1
SLIB= -lm
include $(MAKEBIN)
 





