# Makefile for grplot
# ===================
# Author: R.J.Barnes

INCLUDE=-I$(IPATH)/base -I$(IPATH)/general
SRC=grplot.c
OBJS = grplot.o 
SRC=hlpstr.h errstr.h grplot.c
OBJS = grplot.o 
OUTPUT = $(BINPATH)/grplot
LIBS=-lgrplot.1 -lplot.1 -lfbpsrplot.1 -lrplotin.1 -lrtime.1 -lrplot.1 -lrxml.1 -limagedb.1 -lfontdb.1 -lrfbuf.1 -lrps.1 -lopt.1 
XLIB=-lxwin.1
SLIB= -lm

include $(MAKEBIN)

 

