# Makefile for ppmtoppmx
# ======================
# Author: R.J.Barnes

INCLUDE=-I$(IPATH)/base
OBJS = ppmtoppmx.o
SRC=ppmtoppmx.c hlpstr.h errstr.h
OUTPUT = $(BINPATH)/ppmtoppmx
LIBS=-lrfbuf.1 -lrxml.1 -lopt.1 
SLIB= -lm
include $(MAKEBIN)


 















