# Makefile for OptionFreeText
# ===========================
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/base
IGNVER=1
OBJS = OptionFreeText.o
OUTPUT = OptionFreeText
LIBS= -lopt.1
SLIB= -lm
include $(MAKEBIN)
 





