# Makefile for RfileSeek
# ======================
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/base -I$(IPATH)/general 
IGNVER=1
OBJS = RfileSeek.o
OUTPUT = RfileSeek
LIBS=-lrfile.1 -lrtime.1 -lrcnv.1 
SLIB=-lm
include $(MAKEBIN)
 
