# Makefile for XMLFree
# ========================
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/base -I$(IPATH)/general -I$(IPATH)/superdarn
IGNVER=1
OBJS = XMLFree.o
OUTPUT = XMLFree
LIBS=-lrxml.1
SLIB=-lm
include $(MAKEBIN)