# Makefile for XMLSetProcess
# ========================
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/base -I$(IPATH)/general -I$(IPATH)/superdarn
IGNVER=1
OBJS = XMLSetProcess.o
OUTPUT = XMLSetProcess
LIBS=-lrxml.1
SLIB=-lm
include $(MAKEBIN)