# Makefile for option library
# ===========================
# by R.J.Barnes
#
#
INCLUDE=-I$(IPATH)/base
SRC=option.c printinfo.c 
OBJS = option.o printinfo.o
DSTPATH=$(LIBPATH)
OUTPUT = opt
LINK="1"
include $(MAKELIB)

















