# Makefile for PostScriptMatrixString
# ========================
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/base -I$(IPATH)/general -I$(IPATH)/superdarn
IGNVER=1
OBJS = PostScriptMatrixString.o
OUTPUT = PostScriptMatrixString
LIBS=-lrps.1
SLIB=-lm
include $(MAKEBIN)