# Makefile for RplotImageName
# ========================
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/base -I$(IPATH)/general -I$(IPATH)/superdarn
IGNVER=1
OBJS = RplotImageName.o
OUTPUT = RplotImageName
LIBS=-lrplot.1
SLIB=-lm
include $(MAKEBIN)