# Makefile for XwinFrameBufferToXimage
# =============================
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/base 
IGNVER=1
OBJS = XwinFrameBufferToXimage.o
OUTPUT = XwinFrameBufferToXimage
LIBS=-lrfbuf.1 -lxwin.1 
SLIB=-lm
include $(MAKEBIN)
 
