# Makefile for radar library
# ========================
# by R.J.Barnes
#
#
INCLUDE=-I$(IPATH)/base -I$(IPATH)/general -I$(IPATH)/superdarn
SRC=fitscan.c fitcfit.c fitcsd.c fitread.c fitwrite.c fitseek.c fitinx.c
OBJS = fitscan.o fitcfit.o fitcsd.o fitread.o fitwrite.o fitseek.o fitinx.o
DSTPATH=$(LIBPATH)
OUTPUT = fit
LINK="1"
include $(MAKELIB)



