# Makefile for FrameBufferSaveXML
# ========================
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/base -I$(IPATH)/general 
IGNVER=1
OBJS = FrameBufferSaveXML.o
OUTPUT = FrameBufferSaveXML
LIBS=-lrfbuf.1
SLIB=-lm
include $(MAKEBIN)