# Makefile for PostScriptMake
# ========================
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/base -I$(IPATH)/general -I$(IPATH)/superdarn
IGNVER=1
OBJS = PostScriptMake.o
OUTPUT = PostScriptMake
LIBS=-lrps.1
SLIB=-lm
include $(MAKEBIN)