# Makefile for OldFitACF
# ===============--=====
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/base -I$(IPATH)/general -I$(IPATH)/superdarn 
IGNVER=1
OBJS = OldFitACF.o
OUTPUT = OldFitACF
LIBS=-lfit.1 -lraw.1 -loldfitacf.1 -lradar.1  -lrtime.1 -ldmap.1 -lrcnv.1 
SLIB=-lm
include $(MAKEBIN)
 
