# Makefile for cnvmap library
# ===========================
# by R.J.Barnes
#

INCLUDE=-I$(IPATH)/base -I$(IPATH)/general -I$(IPATH)/superdarn -I$(IPATH)/analysis   
OBJS = readmap.o writemap.o mapseek.o mapinx.o
SRC=  readmap.c writemap.c mapseek.c mapinx.c
LINK="1"
DSTPATH=$(LIBPATH)

OUTPUT = cnvmap
include $(MAKELIB)
 

 





