# Makefile for RplotStartInfo
# ========================
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/base -I$(IPATH)/general -I$(IPATH)/superdarn
IGNVER=1
OBJS = RplotStartInfo.o
OUTPUT = RplotStartInfo
LIBS=-lrplot.1
SLIB=-lm
include $(MAKEBIN)