# Makefile for NNetMakeNet
# =========================
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/general 
IGNVER=1
OBJS = NNetMakeNet.o
OUTPUT = NNetMakeNet
LIBS= -lrnnet.1 -lrcnv.1
SLIB= -lm
include $(MAKEBIN)
 
