# Makefile for Rplot Library
# ===============================
# by R.J.Barnes
#
#
INCLUDE=-I$(IPATH)/base

SRC = matrix.c color.c dash.c make.c bezier.c line.c shape.c polygon.c \
      text.c image.c imagename.c embed.c include.c info.c clip.c plot.c 

OBJS = matrix.o color.o dash.o make.o bezier.o line.o shape.o polygon.o \
      text.o image.o imagename.o embed.o include.o info.o clip.o plot.o
DSTPATH=$(LIBPATH)
OUTPUT = rplot
LINK="1"
include $(MAKELIB)

















