# Makefile for NNetForward
# =========================
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/general 
IGNVER=1
OBJS = NNetForward.o
OUTPUT = NNetForward
LIBS= -lrnnet.1 -lrcnv.1
SLIB= -lm
include $(MAKEBIN)
 
