# Makefile for XMLCallStart
# ========================
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/base -I$(IPATH)/general -I$(IPATH)/superdarn
IGNVER=1
OBJS = XMLCallStart.o
OUTPUT = XMLCallStart
LIBS=-lrxml.1
SLIB=-lm
include $(MAKEBIN)