# Makefile for dmap library
# =========================
# by R.J.Barnes
#
#
INCLUDE=-I$(IPATH)/base -I$(IPATH)/general
SRC=dmap.c
OBJS = dmap.o
DSTPATH=$(LIBPATH)
OUTPUT = dmap
LINK="1"
include $(MAKELIB)

















