# Makefile for Frame Buffer Library
# =================================
# by R.J.Barnes
#
#
INCLUDE=-I$(IPATH)/base
SRC=bezier.c char.c color.c dash.c image.c line.c make.c matrix.c \
    polygon.c ppm.c xml.c shape.c user.c clip.c

OBJS=bezier.o char.o color.o clip.o dash.o image.o line.o make.o matrix.o \
    polygon.o ppm.o shape.o user.o xml.o
DSTPATH=$(LIBPATH)
OUTPUT = rfbuf
LINK="1"
include $(MAKELIB)

















