# Makefile for xmldoc library
# ===========================
# by R.J.Barnes
#
#
INCLUDE=-I$(IPATH)/base
SRC=getstring.c build.c make.c render.c set.c getstring.h
OBJS=getstring.o build.o make.o render.o set.o
DSTPATH=$(LIBPATH)
OUTPUT = rxmldoc
LINK="1"
include $(MAKELIB)

















