# Makefile for RplotFreeDash
# ========================
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/base -I$(IPATH)/general -I$(IPATH)/superdarn
IGNVER=1
OBJS = RplotFreeDash.o
OUTPUT = RplotFreeDash
LIBS=-lrplot.1
SLIB=-lm
include $(MAKEBIN)