# Makefile for fbrplot Library
# ===============================
# by R.J.Barnes
#
#
INCLUDE=-I$(IPATH)/base -I$(IPATH)/base

SRC =  fbrplot.c psrplot.c rplot.c include.c include.h
      
OBJS =  fbrplot.o psrplot.o rplot.o include.o
DSTPATH=$(LIBPATH)
OUTPUT = fbpsrplot
LINK="1"
include $(MAKELIB)

















